[build]
  command = "cd backend && npm install"
  publish = "frontend"
  functions = "backend/netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# Redirecciones para API
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/api/:splat"
  status = 200

# Frontend
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
