[build]
  command = "cd backend && npm install"
  publish = "frontend"
  functions = "backend/netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# Redirecciones para el frontend
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Redirecciones para API (opcionales, ahora usamos las directas)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/api/:splat"
  status = 200

[[redirects]]
  from = "/backend/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
