[build]
  command = "cd backend && npm install"
  publish = "frontend"
  functions = "backend/netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# Redirecciones para tu aplicación
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/api/:splat"
  status = 200

[[redirects]]
  from = "/login"
  to = "/.netlify/functions/server/login"
  status = 200

[[redirects]]
  from = "/index"
  to = "/.netlify/functions/server/index"
  status = 200

[[redirects]]
  from = "/health"
  to = "/.netlify/functions/server/health"
  status = 200

# Todas las demás rutas van al frontend
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
