[build]
  command = "cd backend && npm install"
  publish = "frontend"
  functions = "backend/netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# REDIRECCIONES CORREGIDAS - sin prefijo /server
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/api/:splat"
  status = 200

[[redirects]]
  from = "/health"
  to = "/.netlify/functions/server/health"
  status = 200

[[redirects]]
  from = "/test-firebase"
  to = "/.netlify/functions/server/test-firebase"
  status = 200

# Frontend
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
